name: Deploy to Github Pages
on:
  push:
    branches: ['master']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build Library
        run: yarn build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sample-project
          path: |
            *
            !node_modules
  build-sample:
    runs-on: ubuntu-latest
    needs: build-library
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: sample-project
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: 'example/yarn.lock'
      - name: Install Sample Project Dependencies
        working-directory: example
        run: yarn install --frozen-lockfile
      - name: Build Sample Project
        working-directory: example
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: example/dist
  deploy:
    needs: build-sample

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action